exec: Box the Exec structure
The `Exec` structure is large compared to the others. This causes `just lint`
to complain:

```
error: large size difference between variants
  --> crates/youki/src/main.rs:48:1
   |
48 | / enum SubCommand {
49 | |     // Standard and common commands handled by the liboci_cli crate
50 | |     #[clap(flatten)]
51 | |     Standard(liboci_cli::StandardCmd),
   | |     --------------------------------- the second-largest variant contains at least 104 bytes
52 | |     #[clap(flatten)]
53 | |     Common(liboci_cli::CommonCmd),
   | |     ----------------------------- the largest variant contains at least 320 bytes
...  |
57 | |     Completion(commands::completion::Completion),
58 | | }
   | |_^ the entire enum is at least 320 bytes
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#large_enum_variant
   = note: `-D clippy::large-enum-variant` implied by `-D warnings`
help: consider boxing the large fields to reduce the total size of the enum
   |
53 |     Common(Box<liboci_cli::CommonCmd>),
   |            ~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Boxing the `Exec` variant prevents this problem from happening.

Signed-off-by: Christophe de Dinechin <dinechin@redhat.com>